
server:
    port: 8888
    
spring:
    cloud:
        config:
            server:
                git:
                    uri: file://${user.home}/local/tmp/config-repo
                    
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
